SWM-KAWAI-MANS/party-run-battle-service

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleStatus.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/RunnerAlreadyRunningInBattleException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/global/config/MongoConfig.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
배틀을 생성할 때 이미 진행중인 배틀에 존재하는 러너가 새로운 배틀에 참여하게되면 안되기 때문에, 예외를 던지도록 수정했습니다.
이 과정을 위해서 Battle에 상태(Status)가 들어갑니다.
mongoRepository를 이용하여 findByStatusAndRunnersIn (이름으로 쿼리 생성) 을 만들었습니다.
=> 이미 진행중인 배틀에 존재하는 러너가 새로운 배틀을 생성할 수 없도록 수정한다.

build.gradle, src/docs/asciidoc/index.adoc, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/RunningBattleNotFoundException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/global/config/BattleAuthorizationRegistry.java, src/main/java/online/partyrun/partyrunbattleservice/global/controller/HttpControllerAdvice.java, src/main/java/online/partyrun/partyrunbattleservice/global/exception/BadRequestException.java, src/main/java/online/partyrun/partyrunbattleservice/global/exception/NotFoundException.java, src/main/resources/application.yml, src/test/java/online/partyrun/partyrunbattleservice/acceptance/AcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/acceptance/SimpleRestAssured.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleRestAssuredRequest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
클라이언트가 현재 진행중(running) 상태인 battle 정보를 조회하는 API를 구현하였습니다.
1. security-manager 를 도입하였습니다.
이로인해 서비스간 통신을 해야하는 배틀 생성 요청은 필터에서 제외되도록 변경하였습니다.
```yaml
auth:
filter:
exclusions: "battle"
```
배틀 조회 요청에는 security가 적용됩니다. 따라서 `BattleAuthorizationRegistry`를 추가하였습니다.
2. 인수 테스트 추가
함께 이야기를 나눈 결과 `@WebMvcTest`에서는 우리가 만든 시큐리티 적용이 어렵기 때문에, 시큐리티 적용에 대한 테스트는 인수테스트에서 진행해야겠다고 결론이 나왔습니다.
인수 테스트는 RestAssured를 통해 구현하였습니다.
RestAssured는 더 쉽게 사용할 수 있게 SimpleRestAssured를 만들어, test-manager에 분리할 예정입니다. 
동작 과정을 모르겠으면 바로 물어봐주세요!
=> 클라이언트에게 배틀 정보를 전달한다.

src/main/java/online/partyrun/partyrunbattleservice/global/config/WebSocketConfig.java, src/test/java/online/partyrun/partyrunbattleservice/acceptance/AcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/config/WebSocketTestConfiguration.java
배틀을 진행하기위해서 웹소켓 연결을 해야합니다. 이를 위해 WebSocketConfig 파일을 추가하였습니다.
BattleWebSocketAcceptanceTest를 통해서 어떻게 연결을 진행하는지 확인할 수 있습니다.
클라이언트가 `/battle/ws` 로 웹소켓 요청을 보내면, 웹소켓 연결을 진행합니다.
이 때 스프링 시큐리티가 동작해서 정상적이지 않은 러너가 요청을 한다면, 403 응답을 받게 됩니다.
테스트의 내용은 웹소켓 연결이 성공되었다면, StompSession이 Not Null이 되고, 실패하였다면 예외가 발생합니다.
=> 클라이언트와 서버간의 웹소켓 연결을 진행한다.

build.gradle, src/docs/asciidoc/index.adoc, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/config/BattleChannelInterceptor.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/config/WebSocketConfig.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleWebsocketController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/LocationDto.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/InvalidSubscribeRequestException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/RunnerAlreadyRunningInBattleException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerStatus.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entuty/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entuty/RunnerStatus.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/repository/RunnerRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/service/RunnerService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleRestAssuredRequest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/StompFrameHandlerImpl.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/service/RunnerServiceTest.java
사용자가 인증이 되었어도, 특정 배틀을 구독하는 것에 대해 인가를 해주어야합니다.
내가 속한 배틀이 아니지만 구독을 하려는 경우 구독에 실패하도록 로직을 작성했습니다.
컨트롤러와 테스트는 예시를 위해서 작성했습니다. (완성 아님)
BattleChannelInterceptor는 ChannelInterceptor를 상속받은 것으로, 디스패처 서블릿의 interceptor와 같은 원리입니다.
요청을 먼저 가로채서 배틀과 러너에 대해 확인 후, 검증에 실패하면 예외를 터뜨려 구독에 실패하도록 합니다.
웹소켓 클라이언트를 이용해서 실제 요청을 보내는 방식으로 구현했습니다.
웹소켓은 스레드 방식으로 동작하므로, BlockingQueue를 사용했습니다.
BlockingQueue를 사용하지 않으면 다른 스레드에서 받은 데이터가 날라가요 ,, ,
=> 사용자에 따라 구독을 막을지 설정한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleEventHandler.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/BattleRunningEvent.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/RunnerRunningEvent.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleDao.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleDaoTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerTest.java
현재 러너가 RUNNING 상태로 변경될 때마다, 스프링 이벤트를 발행하고 있습니다.
따라서 ConcurrentHashMap으로 이벤트를 관리하고 있었습니다.
ConcurrentHashMap으로 관리하는 방법에서, 이벤트를 한 번만 날려서 이벤트를 바로 처리하는 로직으로 변경했습니다.
몽고 DB의 `findOneAndUpdate`와 `returnNewDocument` 필드를 사용하여 이벤트를 한 번만 발행하도록 수정 시도해보았습니다.
몽고 DB는 기본적으로 도큐먼트를 수정하는 요청 여러개가 동시에 들어올 때 순차적으로 실행됩니다.
현재 변경된 로직에서 `findOneAndUpdate`를 통해 러너의 상태를 update 하고, 반환합니다.
이때 `returnNewDociment` 설정을 true로 하여, 조회-수정-반환을 원자적으로 실행할 수 있도록 변경했습니다.
즉, 여러 스레드가 동시에 들어와도 조회-수정-반환이 원자적으로 실행되어, 결국 마지막으로 요청한 스레드에만 모든 러너가 RUNNING 상태인 Battle을 조회하게 됩니다.
이 Battle을 조회한 스레드만 Event를 발행하게 됩니다.
[동시성 이슈 해결기2](https://www.notion.so/seongwoo-memo/feat-mongoDB-2-e4f9687fb02f4154a2f53b0e2627797e?pvs=4)
BattleServiceTest에 `러너의_상태를_RUNNING으로_변경할_때 모든_러너의_상태가_변경되었다면 BattleRunningEvent을 publish한다. `
테스트에서 이벤트가 한 번만 발행되는지 테스트를 …
=> Battle 시작 시간을 위한 이벤트를 발행하는 방식을 변경한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/BattleAlreadyFinishedException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/BattleAlreadyRunningException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/BattleIsNotReadyException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/BattleIsNotRunningException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/exception/RunnerAlreadyFinishedException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/exception/RunnerAlreadyRunningException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/exception/RunnerIsNotReadyException.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerTest.java
아침에 말했던 대로 원하는 상태만을 검증하도록 변경했습니다.
만약에 특정 메소드를 실행할 때 `READY` 상태여야한다면, `READY` 상태인지 아닌지에 대해서만 검증하도록 변경했습니다.
이를 통해 기존에 `@Disable`로 처리했던 테스트 코드를 제거하고 테스트 커버리지를 채울 수 있게 되었습니다.
=> battle, runner 의 상태를 검증하는 로직을 변경한다.

src/main/java/online/partyrun/partyrunbattleservice/global/config/BattleAuthorizationRegistry.java, src/main/resources/application.yml
도커 이미지 빌드 시에 rest docs 문서가 안나오는 문제를 해결하려다가..
애초에 rest docs에는 접근 불가능했다라는 것을 발견했습니다.
`spring security`에 의해서 /api/docs/index.html 에 접근할 수 없었습니다.
matching 도 마찬가지로 403 에러가 뜰 것입니다. 이는 추후에 확인해보겠습니다.
이를 해결하기 위해 spring security 라이브러리에서 만든 필터에 url 을 추가하고
해당 url로 접근 시, 모두 허가되도록 구현하였습니다.
=>  spring security에 의해 rest docs 문서가 접근 불가능하던 문제 해결

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerTest.java
이전까지는 좌표를 추가할 때, 목표 거리를 다 달렸는지에 대해서는 확인하지 않았습니다.
이번 PR에서는 좌표를 추가하는 시점에, 목표 거리를 다 달렸다면 러너의 상태를 Finished로 변경하였습니다.
Finished 상태로 변경된 러너는, 더이상 좌표를 추가할 수 없습니다.
즉, 배틀에 더이상 참여할 수 없습니다.
로직적으로 크게 어려운 부분은 없습니다. 
battleRepository의 addRunnerRecordsAndUpdateRunnerStatus 메서드를 통해 좌표를 추가하는 시점에 runner의 상태도 같이 업데이트 합니다. 
runner 가 running 상태일 때는 굳이 update를 진행할 필요가 없습니다. 따라서 service에서 runner가 running 상태라면 addRunnerRecords를 실행하고, finished 상태라면 addRunnerRecordsAndUpdateRunnerStatus를 실행하도록 해야할까요?
아니면 그냥 지금처럼 단순하게 addRunnerRecordsAndUpdateRunnerStatus만 사용하도록 할까요?
=> 러너들에게 좌표를 받고, 목표 거리에 도달 시 러너가 종료 상태가 되도록 변경한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleMessageControllerAdvice.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleMessageExceptionHandler.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/GpsData.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/exception/PastGpsDataTimeException.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/GpsDataTest.java
@ControllerAdvice를 추가했습니다.
클라이언트와의 통신 과정 중, 예외에 대해서 로그를 찍지 않아서 빠르게 확인할 수 없는 문제가 있었습니다.
이를 해결하기 위한 방법으로  간단하게 ExceptionHandler를 구현했습니다.
추가로 에러 핸들러가 잘 동작하는지 확인하다가 새로운 검증 로직이 발견되어서 간단하게 추가해보았습니다.
현재는 log를 찍는 용도로만 사용하지만, 추후에는 유저에게 직접 에러 메시지를 전달하여, 웹소켓 연결을 끊는 작업을 유도할 것 입니다.
=> 배틀 웹소켓 통신 과정 중, 발생하는 예외를 처리한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/entity/Battle.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/exception/InvalidBattleCreatedAtException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleDaoTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
Battle에서 생성 날짜를 저장하는 로직이 `@CreatedDate`로 설정되어있었습니다.
따라서 DB에 저장되는 시점에 DB 시간에 맞게 createdAt 필드가 설정되었습니다.
따라서 DB 서버 시간을 변경하려고 했지만, 실패했습니다.
MongoDB Atlas는 완전 관리형 데이터베이스이므로 서버 설정이 불가능한 것으로 판단합니다.
=> @CreatedDate를 삭제한다.

src/docs/asciidoc/battle.adoc, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/config/WebSocketConfig.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/FinishedBattleResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/FinishedRunnerResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/exception/RunnerIsNotFinisedException.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerTest.java
러너가 배틀을 종료하고, 배틀의 결과 페이지를 확인해야합니다.
이를 위한 데이터를 응답하는 API를 만들었습니다.
현재는 이 API에서 목표 거리, 시작 시간, 등수, 종료 시간을 응답합니다.
추후에 이 API에서 Gps 좌표들도 반환해야합니다.
1. 이 API 를 제대로 테스트하려면, 웹소켓 테스트와 인수 테스트를 합쳐야하는데, 시간이 없으므로 Controller 테스트까지만 진행했습니다.
2. 결과에는 종료된 상태의 러너에 대해서만 반환합니다. 달리고 있는 상태의 러너는 조회 대상에서 제외됩니다.
=> 배틀 결과를 조회한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/MessageResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
앱을 실행했을 때, 매칭이나 다른 기능을 사용하려면 러너가 배틀에 속해있는지 확인해야합니다.
만약 속해있다면 종료시켜야합니다.
이를 위한 API 를 만들었습니다.
추후에는 앱 강제종료 시, 재연결을 하도록 기능을 변경할 예정입니다.
이 API도 변경되겠죠?
=> 러너가 배틀에 속해있다면 종료시킨다.

build.gradle, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/SqsMessage.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/SqsMessageListener.java, src/main/java/online/partyrun/partyrunbattleservice/domain/member/service/MemberService.java, src/main/resources/application.yml, src/test/java/online/partyrun/partyrunbattleservice/domain/member/service/MemberServiceTest.java
멤버 서비스에서 멤버가 생성되면, 멤버에서 생성되었다는 이벤트를 전송합니다. 
[멤버 생성 시 이벤트 전송 PR](https://github.com/SWM-KAWAI-MANS/party-run-authentication-service/pull/23)
Sqs로부터 이 이벤트를 받아서 멤버를 생성합니다.
배틀에서 멤버가 존재해야 러너를 생성할 수 있습니다.
```java
@SqsListener(value = "${spring.cloud.aws.sqs.queue-url}")
public void receive(String message) throws JsonProcessingException {
JsonNode jsonNode = objectMapper.readTree(message);
final String event = jsonNode.get("Message").asText();
final SqsMessage sqsMessage = objectMapper.readValue(event, SqsMessage.class);
if (sqsMessage.isCreatedMessage()) {
memberService.save((String) sqsMessage.value());
}
}
```
SqsMessageListner의 메소드에서 파라미터로 객체를 넣을 수 있는 것 같습니다. 객체를 넣는다면 objectMapper를 사용할 필요가 없습니다.
그런데 제가 하니까 안되더라구요.
그래서 빠르게 구현하기 위해서 objectMapper를 사용했습니다.
추후에 변경이 되어야합니다.
그리고 테스트를 실행해보면 sqs 로부터 …
=> 멤버 생성 이벤트를 통해 멤버를 저장한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerRecordResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/HaversineDistanceCalculator.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
우리는 지도에 각 러너의 GPS 기록을 조회해야합니다.
하지만, 현재까지는 등수에 대한 정보만 주었습니다.
이 PR에서 결과 조회 시, GPS 기록도 전달하도록 구현하였습니다.
이를 통해 안드로이드에서 구글 지도 상에 GPS 기록을 띄울 수 있게 됩니다.
Response를 생성하는 로직을 Response 내부에서 처리하도록 변경하였습니다.
결과 조회 요청이 들어오면 아래와 같은 형식으로 응답이 전달됩니다.
=> 결과 조회 시, 각 러너의 GPS 기록을 조회한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/GpsData.java, src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/entity/BattleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/RunnerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/GpsDataTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecordTest.java, src/test/java/online/partyrun/partyrunbattleservice/fixture/GpsDataFixture.java, src/test/java/online/partyrun/partyrunbattleservice/fixture/LocalDateTimeFixture.java
기존에는 GPS 좌표가 튀는 현상을 막지 못하였습니다.
속력 제한은 GPS 좌표 보정 과정 중, 첫 번째 작업입니다.
GPS 좌표를 통해 새로운 기록을 만들 때, 속력 제한 기능을 두어 제한 속력을 넘어가면 해당 GPS 좌표를 무시하도록 했습니다. 
Runner, RunnerRecord, GpsData 3개를 집중적으로 보면 좋을 것 같아요.
로직이 조금 더러워서 로직적으로도 신경써서 봐주세요.
속력 제한을 넣기 전의 테스트들은 모두 속력 제한이 없었기 때문에, 데이터 값을 모두 변경했어야했습니다.
따라서 file change가 많다고 생각이 될 것입니다.
하지만 이를 분리할 수는 없습니다.
기존의 방식과 속력 제한 기능이 추가된 방식을 비교해야합니다.
안드로이드에서 직접 확인해야합니다.
이전 버전을 먼저 테스트하고 이 PR을 머지할 예정입니다.
=> 배틀 진행 시, GPS 좌표에 속력 제한 기능을 추가한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleDaoTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
기존에 러너의 상태를 변경하기 위해 사용했던 메서드는 아래와 같습니다.
```java
@Query(value = "{'runners.id': ?0, 'runners.status': { $in: ?1 }}")
@Update("{'$set' :  {'runners.$.status': ?2}}")
void updateReadyOrRunningRunnerStatus(
String runnerId, List<RunnerStatus> preRunnerStatus, RunnerStatus runnerStatus);
```
1. @Query(value = "{'runners.id': ?0, 'runners.status': { $in: ?1 }}") 를 통해서 Battle을 찾는다.
2. @Update("{'$set' :  {'runners.$.status': ?2}}") 를 통해서 조회된 Battle의 첫 번째 Runner의 status를 변경한다.
이전에는 이 쿼리가 runners.id에 해당하는 runner의 상태를 변경할 것이라고 예상했습니다.
하지만 첫 번째 Runner의 status만 변경했고, 따라서이를 사용하지않게 되었습니다.
1. 하나의 쿼리로 수정 시도
```java
public void updateRunnerStatus(String runnerId, List<RunnerStatus> preStatus, RunnerStatus runnerStatus) {
Query query = Query.query(where("runners").elemMatch(where("id").is(runnerId).and("sta …
```
=> 러너의 상태를 변경하는 로직 버그 해결

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/event/WebSocketEventListener.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepository.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/repository/BattleRepositoryTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java
배틀 생성 시, runner들 중, READY 상태나 RUNNING 상태인 러너가 존재한다면 배틀이 생성될 수 없도록 하는 로직 중, 
existsByRunnersIdInAndRunnersStatusIn 쿼리에 문제가 있었습니다.
아래처럼 배틀 도큐먼트가 존재한다고 가정해보겠습니다.
```
배틀 {
러너 : [
{ 
id : 박성우,
status: RUNNING
},
{
id: 노준혁,
status: FINISHED
}
]
}
```
노준혁이 FINISHED 라면 `existsByRunnersIdInAndRunnersStatusIn(["박현준", "노준혁"],  ["READY", "RUNNING"])` 가 false를 반환하는 것을 기대했습니다.
기존의 existsByRunnersIdInAndRunnersStatusIn를 실행했을 때, 아래처럼 쿼리가 실행됩니다.
{ "runners._id" : { "$in" : ["박현준", "노준혁"]}, "runners.status" : { "$in" : ["READY", "RUNNING"]}} 
위 쿼리는 runners._id 가 ["박현준", "노준혁"] 인 Battle을 찾고, 그 Battle에서 runners의 status 중 "READY", "RUNNING" 이 존재한다면 true를 반환합니다.
즉, 아래의 배틀 도큐먼트가 존재한다면, existsByRunnersIdInAndRunnersStatusIn 이 true를 반환하는 것입니다.
따라서 mongoDB의 `elemMatch`를 사용하여 이를 해결하였습니다.
기존의 …
=> 러너들의 id와 상태를 통해 조건에 맞는 배틀이 존재하는지 확인한다.

src/main/java/online/partyrun/partyrunbattleservice/global/advisor/LogAdvisor.java
매칭에서 진행했던 LogAdvisor를 그대로 가져왔습니다.
하지만 조금 다른 부분이 있습니다.
1. info 레벨로 로그를 생성한다.
실행 정보를 알려주는 것이라 생각해서 info 로 설정했습니다.
2. 요청, 응답을 모두 표시한다.
메시지 형식이 올바른지는 모르겠습니다만, 요청과 응답을 모두 로그로 나타내야한다고 생각했습니다.
=> feat: 전체 메서드에 대해 실행 로그를 작성하는 Advisor 구현

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/config/BattleChannelInterceptor.java, src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleWebsocketController.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java
이전에는 구독 이후, 준비가 완료되었다는 요청을 추가로 보냈어야했습니다.
이를 구독 요청이 들어오면 interceptor에서 준비 완료를 처리하는 로직으로 변경하였습니다.
이렇게 함으로써 불필요한 로직, 트래픽을 줄이게 되었습니다.
로직에서 큰 변화는 없습니다. 컨트롤러에 존재하던 로직을 인터셉터로 옮긴 것 뿐입니다.
=> battleInterceptor BATTLE_TOPIC_PREFIX 변경

src/main/java/online/partyrun/partyrunbattleservice/domain/battle/controller/BattleMessageControllerAdvice.java
다른 서비스와 마찬가지로 `@ControllerAdvice`에서 예외마다의 처리를 변경했습니다.
앞으로 점차 로깅에 대해서 발전시켜나가야합니다.
예외 처리는 다른 서비스와 동일하게 진행했습니다. 
추후에는 예외가 발생하면 러너들에게 어떻게 전달할지에 대해서 고민해볼 생각입니다.
=> 배틀 과정 중 예외 발생 시, 로깅 처리

src/main/java/online/partyrun/partyrunbattleservice/global/config/RedissonConfig.java, src/main/resources/application.yml, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/config/TestRedissonConfiguration.java
production 환경에서는 redis cluster를 사용합니다.
그에 맞게 연결 방법도 변경해야합니다.
Redisson을 사용하고 있으므로 Redisson client를 수정하였습니다.
고민되는 부분은 prd와 dev환경에서 Redisson client가 다르다는 부분인데요.
test 까지는 단일 레디스로 가도 될 것 같다고 생각이 드는데,
dev 환경을 위해서 production 코드에 dev만의 bean 이 등록되는게 좀 이상해서요.
사실 dev 환경이 prd 환경과 다른 것도 좀 이상하고?
만약 dev 환경을 지금 그대로 유지한다면, 지금처럼 설정 파일을 가져가야할 것 같고,
dev 환경에서도 레디스 클러스터를 구축한다면 설정 파일을 다시 변경해야할 것 같고.
어떤게 좋을 것 같은가요?
=> feat: redis cluster 연결을 prd 환경 변수 변경

src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/acceptanceTest/BattleWebSocketAcceptanceTest.java
속도 제한 기능이 추가되면서 새롭게 발생한 버그가 있습니다.
기존 로직에서는 
`Collections.max(this.runnerRecords)` 를 그냥 진행하고 있었습니다.
하지만 속도 제한 기능이 추가되면서 this.runnerRecords가 null일 수 있습니다. 속도 제한에 걸린 GPS들은 Records에 추가되지 않기때문입니다.
=> 거리 계산 로직 수정

src/docs/asciidoc/battle.adoc, src/main/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleIdResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordRequest.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequest.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/Single.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/SingleRunnerRecordEmptyException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/repository/SingleRepository.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java, src/main/java/online/partyrun/partyrunbattleservice/global/controller/HttpControllerAdvice.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/SingleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleServiceTest.java
싱글 모드의 데이터를 저장하는 API를 만들었습니다.
싱글 데이터에 관한 검증 로직을 거의 추가하지 않았습니다.
1. 안드로이드 측에서 이미 검증을 하고 보내는 데이터이므로
2. 싱글 모드는 클라이언트 측에서 일시 정지, 재시작 등이 존재하므로 검증을 하기에 어려움
=> 싱글 모드 기록을 저장한다.

src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequest.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleRunnerRecordsRequestTest.java
기존에 : SingleRunnerRecordsRequest parse 시에 문제가 발생했습니다.
test코드에서 request body를 확인해보니 RunnerRecords도 같이 파싱하는 것을 확인했습니다.
따라서 기존 메서드에서 get 부분을 제거하고, record 스타일에 맞게 runnerRecords()로 변경하였습니다. 변경 이후에는 테스트를 통과하는 것을 확인할 수 있었습니다.
=> refactor : SingleRunnerRecordsRequest 메서드명 변경

src/docs/asciidoc/battle.adoc, src/main/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleController.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/RunningTimeResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/dto/SingleResponse.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/entity/Single.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/InvalidSingleOwnerException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/exception/SingleNotFoundException.java, src/main/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleService.java, src/test/java/online/partyrun/partyrunbattleservice/domain/battle/service/BattleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/controller/SingleControllerTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/entity/SingleTest.java, src/test/java/online/partyrun/partyrunbattleservice/domain/single/service/SingleServiceTest.java, src/test/java/online/partyrun/partyrunbattleservice/global/ServiceTest.java
싱글 모드에 대해서 조회하는 로직을 구현하였습니다.
단순 조회 로직입니다.
ServiceTest클래스를 생성하여, 배틀과 싱글의 serviceTest 가 상속받도록 구현하였습니다.
싱글 생성 시에는 문제가 없었는데, 싱글 조회를 하려다보니까 빈 생성 부분에서 문제가 생기네요. 빈 생성 부분에 문제가 있을거면 진작에 있었어야했는데 이유를 모르겠네요 . .ㅋ
=> 싱글 결과 조회 API 구현

src/main/java/online/partyrun/partyrunbattleservice/domain/mypage/dto/MyPageTotalResponse.java
배틀 생성만 하고 기록이 없는 경우 에러 처리했습니다~
=> 배틀 생성만 하고 기록이 없는 경우 에러 처리
